# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno then run Deno lint and test.
# For more information see: https://github.com/denoland/setup-deno

name: Bun

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Bun
        uses: xhyrom/setup-bun@v0.1.3
        with:
          bun-version: latest
      
      - name: Run install
        run: bun install

      - name: Run typecheck
        run: bun typecheck

      - name: Run linter
        run: bun lint
